
include:
  - board: akdk_bt1
    shield: bksk60_cherry
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artificial-name: BKSK60_cherry
  - board: akdk_bt1
    shield: settings_reset
    artificial-name: settings_reset-akdk_bt1-zmk
